title: ContainerDays Boston 2016
author:
  name: ContainerDays Boston 2016 organizers
  email: '2015-boston@dynamicinfradays.org'
metadata:
    description: The website of the Boston, 2016 edition of the community container (un)conference

