title: DynamicInfraDays Boston
author:
  name: Andrew Phillips
  email: 'info@dynamicinfradays.org'
metadata:
    description: 'DynamicInfraDays will be a community-based conference focused on the emerging possibilities of dynamic infrastructure, including containers and other technologies. The format is likely to follow that of the excellent devopsdays events'

