title: ContainerDays Boston 2015
author:
  name: ContainerDays Boston 2015 organizers
  email: '2015-boston@dynamicinfradays.org'
metadata:
    description: The website of the Boston, 2015 edition of the community container (un)conference

